Sleep(2000)
ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\Users\malhari\Documents\QtalkTestcase.xlsx")
Sleep(2000)
ControlFocus("Open","","Button1")
ControlClick("Open","","Button1")
